#!/bin/sh

# Mirrors builservice repos. Meant to be run daily.
#
#  -- m.barnaba@ifad.org  Sat Mar 29 16:46:48 CET 2014
#
source $(dirname $(realpath $0))/.config.buildservice.subr
create_lock

mirror_repo() {
  REPO="$1"

  echo
  echo "--------------------------------------------------------------"
  echo "`date` - OpenSuSE buildservice $REPO mirror started"


  mkdir -p $MIRROR_DIR/$REPO
  cd $MIRROR_DIR

  $RSYNC --verbose --human-readable --no-motd                     \
       --recursive --links --perms --times                        \
       --itemize-changes --stats                                  \
       --exclude 'openSUSE_*/src'  --exclude 'openSUSE_*/src/**'  \
       --include 'openSUSE_Leap_*' --include 'openSUSE_Leap_*/**' \
       --exclude 'RHEL_*/src'      --exclude 'RHEL_*/src/**'      \
       --include 'RHEL_*'          --include 'RHEL_*/**'          \
       --exclude 'SLE_*/src'       --exclude 'SLE_*/src/**'       \
       --include 'SLE_*'           --include 'SLE_*/**'           \
       --exclude 'rpm/src'         --exclude 'rpm/src/**'         \
       --include 'rpm'             --include 'rpm/**'             \
       --include 'repodata'        --include 'repodata/**'        \
       --include '*.repo'                                         \
       --exclude '*'                                              \
       $RSYNC_HOST/$REPO/ $MIRROR_DIR/$REPO

  ret=$?

  echo "`date` - OpenSuSE buildservice $REPO mirror completed with status $ret"
  echo "--------------------------------------------------------------"
  echo
}

for repo in $BUILDSERVICE_REPOS; do
  mirror_repo $repo
done

replace_repo_uris $MIRROR_DIR
exit $ret
