#!/bin/sh

# Mirrors the Evergreen repository for 11.4. Meant to be run daily.
#
#  -- m.barnaba@ifad.org  Tue Jan  7 17:06:49 CET 2014
#
source $(dirname $(realpath $0))/.config.subr
create_lock

VERSION=11.4
# Keep the trailing slash, or an excess standard/ directory will be created
SOURCE=openSUSE:/Evergreen:/$VERSION/standard/
REPO_DIR=$MIRROR_DIR/repositories/$SOURCE

echo
echo "--------------------------------------------------------------"
echo "`date` - OpenSuSE evergreen 11.4 started"

mkdir -p $REPO_DIR

$RSYNC --verbose --human-readable             \
     --recursive --links --perms --times      \
     --itemize-changes --stats --delete-after \
     --exclude rpm/src                        \
     $RSYNC_HOST::$RSYNC_EVERGREEN_ROOT/$SOURCE $REPO_DIR

ret=$?

echo "`date` - OpenSuSE mirror completed with status $ret"
echo "--------------------------------------------------------------"
echo

replace_repo_uris
exit $ret
