#!/bin/bash

# Mirrors the full netdata repos.
#
#  - m.barnaba  Thu May 14 16:43:53 CEST 2020
#

source $(dirname $(realpath $0))/.config.netdata.subr
create_lock

download_yum_gpg_key() {
  destdir=$1

  curl -Lso $destdir/RPM-GPG-KEY \
    https://packagecloud.io/netdata/netdata/gpgkey
}

mirror_netdata_yum() {
  dir=$1
  repo=netdata-$1
  dst=$MIRROR_DIR/$dir

  echo
  echo "--------------------------------------------------------------"
  echo "`date` - NETDATA repo $repo mirror started to $dst"

  mkdir -p $dst

  [ ! -L $dst/$repo ] && ln -sf . $dst/$repo # HACK

  echo "Syncing packages..."
  reposync --quiet --gpgcheck --repoid=$repo --download_path=$dst

  echo "Creating repo metadata..."
  createrepo $dst

  ret=$?

  echo "`date` - NETDATA repo $repo to $dst mirror completed with status $ret"
  echo "--------------------------------------------------------------"
  echo

  download_yum_gpg_key $(dirname $dst)
}

# mirror repos
#
for repo in $REPOS ; do
  mirror_netdata_yum $repo
done
