#!/bin/sh

# Mirrors the Elastic repos. Meant to be run daily.
#
#  -- m.barnaba@ifad.org  Tue Apr 23 14:40:29 CEST 2019
#
source $(dirname $(realpath $0))/.config.elastic.subr
create_lock

mirror_repo() {
  REPO="$1"

  echo
  echo "--------------------------------------------------------------"
  echo "`date` - Elastic $REPO mirror started"

  mkdir -p $MIRROR_DIR

  echo "Syncing packages..."
  reposync -n -q -g -r $REPO -p $MIRROR_DIR

  echo "Creating repo metadata..."
  createrepo $MIRROR_DIR/$REPO

  echo "Regenerating .repo file..."
  cat <<EOF > $MIRROR_DIR/${REPO}.repo
[$REPO]
name=Elastic repository $REPO
baseurl=$MIRROR_URL/$REPO
gpgcheck=1
gpgkey=$MIRROR_URL/GPG-KEY-elasticsearch
enabled=1
autorefresh=1
type=rpm-md
EOF

  echo "`date` - OpenSuSE buildservice $REPO mirror completed"
  echo "--------------------------------------------------------------"
  echo

}

# Mirror repos
for repo in $ELASTIC_REPOS; do
  mirror_repo $repo
done
