#!/bin/sh

# Mirrors the opensuse distribution. Meant to be run daily.
#
#  -- m.barnaba@ifad.org  Tue Feb 19 19:52:47 CET 2013
#  -- m.barnaba@ifad.org  Tue Jan  7 19:07:55 CET 2014
#
source $(dirname $(realpath $0))/.config.subr
create_lock
create_filter

echo
echo "--------------------------------------------------------------"
echo "`date` - OpenSuSE mirror started"

# Include only update and distribution repos for
# selected releases. TODO: generate the filters
# list from a configuration variable.
#
$RSYNC --verbose --human-readable             \
     --recursive --links --perms --times      \
     --itemize-changes --stats --delete-after \
     --filter "merge $FILTER"                 \
     --exclude='*'                            \
     $RSYNC_HOST::$RSYNC_FULL_ROOT/ $MIRROR_DIR

ret=$?

echo "`date` - OpenSuSE mirror completed with status $ret"
echo "--------------------------------------------------------------"
echo

# Update URLs in .repo files in update/ repos
find $MIRROR_DIR/update/*[1-9]/*.repo -print0 |
  xargs -0 sed -Ei "s#https?://download.opensuse.org/repositories/openSUSE:/([0-9\\.]+):/Update/standard#http://$LOCAL_HOST/update/\\1#"

# Update URLs in .repo files in non-free update/ repos
find $MIRROR_DIR/update/*-non-oss/*.repo -print0 |
  xargs -0 sed -Ei "s#https?://download.opensuse.org/repositories/openSUSE:/([0-9\\.]+):/NonFree:/Update/standard#http://$LOCAL_HOST/update/\\1-non-oss#"

# Update URLs in content.xml files in distribution/ repos
find $MIRROR_DIR/distribution/*/repo/*/control.xml -print0 |
  xargs -0 sed -i \
  -e "s#http://download.opensuse.org/update/#http://$LOCAL_HOST/update/#" \
  -e "s#http://download.opensuse.org/distribution/#http://$LOCAL_HOST/distribution/#"

exit $ret
