#!/bin/sh

# Mirrors the opensuse distribution. Meant to be run daily.
#
#  -- m.barnaba@ifad.org  Tue Feb 19 19:52:47 CET 2013
#  -- m.barnaba@ifad.org  Tue Jan  7 19:07:55 CET 2014
#
source $(dirname $(realpath $0))/.config.subr
create_lock

echo
echo "--------------------------------------------------------------"
echo "`date` - OpenSuSE mirror started"

# Exclude 11.4 to avoid having it deleted, and exclude:
#
# * repositories/ fetched by mirror-buildservice-repo
# * evergreen/    fetched by mirror-evergreen-repo
#
$RSYNC --verbose --human-readable        \
     --recursive --links --perms --times      \
     --itemize-changes --stats --delete-after \
     --exclude='osc/'                         \
     --exclude='ports/'                       \
     --exclude='evergreen/'                   \
     --exclude='repositories/'                \
     --exclude='update/11.0/'                 \
     --exclude='update/11.1/'                 \
     --exclude='update/11.2/'                 \
     --exclude='update/11.3/'                 \
     --exclude='update/11.4/'                 \
     --exclude='distribution/11.0/'           \
     --exclude='distribution/11.1/'           \
     --exclude='distribution/11.2/'           \
     --exclude='distribution/11.3/'           \
     --exclude='distribution/11.4/'           \
     $RSYNC_HOST::opensuse-full/opensuse/ $MIRROR_DIR

ret=$?

echo "`date` - OpenSuSE mirror completed with status $ret"
echo "--------------------------------------------------------------"
echo

# Update URLs in .repo files in update/ repos
ls -1 $MIRROR_DIR/update/*/*.repo |
  xargs sed -i "s#download.opensuse.org#$LOCAL_HOST#"

# Update URLs in content.xml files in distribution/ repos
ls -1 $MIRROR_DIR/distribution/*/repo/*/control.xml |
  xargs sed -i \
  -e "s#http://download.opensuse.org/update/#http://$LOCAL_HOST/update/#" \
  -e "s#http://download.opensuse.org/distribution/#http://$LOCAL_HOST/distribution/#"

exit $ret
