#!/bin/sh

# Mirrors the opensuse distribution. Meant to be run daily.
#
#  -- m.barnaba@ifad.org  Tue Feb 19 19:52:47 CET 2013
#  -- m.barnaba@ifad.org  Tue Jan  7 19:07:55 CET 2014
#
source $(dirname $(realpath $0))/.config.subr
create_lock

echo
echo "--------------------------------------------------------------"
echo "`date` - OpenSuSE mirror started"

# Include onlu update and distribution repos for
# selected releases. TODO: generate the filters
# list from a configuration variable.
#
$RSYNC --verbose --human-readable             \
     --recursive --links --perms --times      \
     --itemize-changes --stats --delete-after \
     -f 'include update/'                     \
     -f 'include update/12.1'                 \
     -f 'include update/12.1/**'              \
     -f 'include update/12.2'                 \
     -f 'include update/12.2/**'              \
     -f 'include update/12.3'                 \
     -f 'include update/12.3/**'              \
     -f 'include update/13.1'                 \
     -f 'include update/13.1/**'              \
     -f 'include distribution/'               \
     -f 'include distribution/12.1'           \
     -f 'include distribution/12.1/**'        \
     -f 'include distribution/12.2'           \
     -f 'include distribution/12.2/**'        \
     -f 'include distribution/12.3'           \
     -f 'include distribution/12.3/**'        \
     -f 'include distribution/13.1'           \
     -f 'include distribution/13.1/**'        \
     --exclude='*' \
     $RSYNC_HOST::$RSYNC_FULL_ROOT/ $MIRROR_DIR

ret=$?

echo "`date` - OpenSuSE mirror completed with status $ret"
echo "--------------------------------------------------------------"
echo

# Update URLs in .repo files in update/ repos
ls -1 $MIRROR_DIR/update/*/*.repo |
  xargs sed -Ei sed -E "s#https?://download.opensuse.org/repositories/openSUSE:/(13.1):/Update/standard#http://$LOCAL_HOST/update/\\1#"

# Update URLs in content.xml files in distribution/ repos
ls -1 $MIRROR_DIR/distribution/*/repo/*/control.xml |
  xargs sed -i \
  -e "s#http://download.opensuse.org/update/#http://$LOCAL_HOST/update/#" \
  -e "s#http://download.opensuse.org/distribution/#http://$LOCAL_HOST/distribution/#"

exit $ret
