#!/bin/sh

# Mirrors the full centos repo.
#
#  - m.barnaba  Tue Apr  2 19:27:48 CEST 2019
#

source $(dirname $(realpath $0))/.config.centos.subr
create_lock

echo
echo "--------------------------------------------------------------"
echo "`date` - CentOS mirror started"

$RSYNC --verbose --human-readable          \
       --recursive --links --perms --times \
       --itemize-changes --stats --delete  \
       --exclude '*/*/ppc64le' \
       --exclude '*/*/aarch64' \
       --exclude '8-stream/isos' \
       --exclude '7Server' \
       --exclude '8Server' \
       $RSYNC_HOST $MIRROR_DIR

ret=$?

ln -nsf 7 $MIRROR_DIR/7Server
ln -nsf 8 $MIRROR_DIR/8Server

echo "`date` - CentOS mirror completed with status $ret"
echo "--------------------------------------------------------------"
echo

exit $ret
